### ISSUE TITLE
Adding 3rd party package

### ISSUE THREAD

**Issue by zivkaziv** [darpanpathak/MEAN2-MarvelApp#1]
Hi,
First I must say that your boilerplate is awesome! Thanks.
Second, I'm trying to use it and add videogular2.
I've run the command **npm install videogular2 --save** so now i have this package installed
I've Added in the **app.module.ts** the relevant imports

My question is how to add the new js files(of videogular2) to "build" process?

**Comment by darpanpathak** [comment]
Hi,

Thanks for using my boilerplate. 

Question : how to add the new js files(of videogular2) to "build" process?
Answer: You don't have to add files to "build". You can directly use the node_modules. For that, you have to define path and variable in the system.config.js file. 

Check map object and packages object in system.config.js file

**Comment by zivkaziv** [comment]
Thanks a lot for your answer.. I'll check how StstemJS works and use it:) thanks

**Comment by paruvellyvishwanath** [comment]
how to build production Mode?and how to change my port 4002 to 3000.
Thank in advance

**Comment by darpanpathak** [comment]
Hi @paruvellyvishwanath,

For this boilerplate, I have not used staging or production/development mode. But, the same version can be used in a production mode with little bit of changes. 

You can change the port in gulp file and server.js file

**Comment by darpanpathak** [comment]
Hi @zivkaziv 

I have added videogular2 plugin in this application. Check the updated code now. I am closing this issue for now, in case you face any problem, contact me.

**Comment by zivkaziv** [comment]
Thanks a lot:)
After your response,I've found how to add it..

Thanks again for your help!
You've created an awesome boilerplate
